/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: f6a639a6-6251-4abd-b53c-ad52a52e3acd
*/

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace currencyAPI.ControllersTests
{
	[TestClass]
	public class GetCurrenciesForTodayTestCase
	{
#region Test methods
		[TestMethod]
		public async Task GetCurrenciesForTodayTest()
		{
			var tests = this.GetDataForExpectedReturnValueTests();
			foreach (var data in tests)
			{
				var parameters = data.Params;
				var actual = await data.ObjectUnderTest.GetCurrenciesForToday(parameters.Date, parameters.State);
				Assert.AreEqual(data.ExpectedValue, actual, data.Name);
			}
		}
#endregion

#region Test data
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public IEnumerable<ExpectedValueTestData<IEnumerable<currencyAPI.Models.GetCurrencyOrdered>>> GetDataForExpectedReturnValueTests()
		{
			yield return new ExpectedValueTestData<IEnumerable<currencyAPI.Models.GetCurrencyOrdered>>
			{
				Name = @"1",
				ObjectUnderTest = null,
				Params = new Parameters
				{
					Date = new DateTime(2022, 7, 22, null),
					State = 1
				},
				ExpectedValue = null
			};
		}
#endregion

#region Types
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public struct ExpectedValueTestData<TExpected>
		{
			public string Name;
			public currencyAPI.Controllers.CurrencySelectionController ObjectUnderTest;
			public Parameters Params;
			public TExpected ExpectedValue;
		}

		public struct Parameters
		{
			public DateTime Date;
			public int State;
		}
#endregion
	}
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAAAO1VW28SQRR+hoT/cGxfaAOLpYJRWmJDqfJAIWVrYowPw86hjC6zODNb3Jj+d8/ZXS6LrfHBpC8SAjP
nfvm+TOO4Uj6GyxFcj3wYji4HV5/A/zCYQG80HPavfda+R41GOJQwTUDi/YLOLPfROlhEEsO3MGuL9ukb0a63m62T+i
sxlfVp6zSoC9lqilYTT0UgyadRKVfKsVX6DiaJdbjoFK9eLwpDDJyKtPXSvCrYN7nBWW6yr/HnBoUkgecL+81u1EMVm
MhGM+d9VDYW4cTFUkUe1+9HUWi9W60c38i4wxVqsUC7FAFCEBuDOkguxgOqTTvD9RnLxrZS/lkplz7zuRcKa7/QbRlP
QxVAwHcanOtl/grtVWT8SIokNReWJlgi90ODd9RJPkt080hS3FIWdZjeOew6rrCJDoC7ezp49YgduLRS6V4YcFwrnIO
bK56puxROkH3/x5KmiPIGXWz0RxHGmHZVPeqkrrOIhhnMocoxJPmA0lmsNH6eIM2wFIYG5mgulIZNvTFLbGdrIgJHgy
e1WAnlMqPR9CtVcKslGs7sPdpRdRvco8qxtpPNmziS5PWWLqxF47wLg/3vlKua5lh3mfZXy8uoZfmvKUzu/MC/9HOIW
mYbYRgUlsMulXKjcf5cH04+DpGgw6RTsyTdKNiMCxDpMElXNEcYMilRKhcZ0JGDORpc6wLS1WCKgYgpUkQis1J0oq2s
VBhCJl+guWNbPSPYOfvimTvfEGDQ1zHVJqYhnhV2yztiZJ/tWuyyN52J3QFZMjKEPJTdbhf+hhZbViUKQwkmtQCNK/h
nlewyi+FJhHl3cHJQyyR7hCGljsMwV2aUYxkVNN5wJFPmIUvMoNyEj75aYLX5stmswesa8B8HPMojllJ6kflJdn/I5Y
Vu8yIyFnX+TKNkifY/hZ6p8w2FrDNx4J7ArL8Wd7dw3/rxY8qw7OzKn3givTW4J5g/11sl7CG5EG+LXdh9RnLtpsBiA
2vk/d5nkQqFjtYUSA+FLEo7SNH/GKL5Tt9fc/IXrzsJAAA=
END_CODEGEN_DATA
*/
