/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: f6a639a6-6251-4abd-b53c-ad52a52e3acd
*/

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace currencyAPI.ControllersTests
{
	[TestClass]
	public class GetCurrenciesForTodayTestCase
	{
#region Test methods
		[TestMethod]
		public async Task GetCurrenciesForTodayTest()
		{
			var tests = this.GetDataForExpectedReturnValueTests();
			foreach (var data in tests)
			{
				var parameters = data.Params;
				var actual = await data.ObjectUnderTest.GetCurrenciesForToday(parameters.Date, parameters.State);
				Assert.IsNotNull( actual);
			}
		}
#endregion

#region Test data
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public IEnumerable<ExpectedValueTestData<IEnumerable<currencyAPI.Models.GetCurrencyOrdered>>> GetDataForExpectedReturnValueTests()
		{
			yield return new ExpectedValueTestData<IEnumerable<currencyAPI.Models.GetCurrencyOrdered>>
			{
				ObjectUnderTest = new currencyAPI.Controllers.CurrencySelectionController(),
				Params = new Parameters
				{
					Date = new DateTime(2022, 7, 22),
					State = 1
				}
			};
		}
#endregion

#region Types
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public struct ExpectedValueTestData<TExpected>
		{
			public currencyAPI.Controllers.CurrencySelectionController ObjectUnderTest;
			public Parameters Params;
		}

		public struct Parameters
		{
			public DateTime Date;
			public int State;
		}
#endregion
	}
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAAAO1VW28SQRR+hoT/cGxfaAOLpYJRWmLTUuWBQsq2iTE+DDuHMrrM4sxscWP63z1nd7kstsYYk77YNGT
mXL5zme+DxmGlfAgXQ7ga+jAYXvQvP4L/oT+G8+Fg0Lvy2fseNRrhUMIkAYn3czqz3UfrYB5JDN/CtC3ax29Eu95uto
7qr8RE1iet46AuZKspWk08FoGknEalXCnHVuk7GCfW4bxTvHrnURhi4FSkrZfWVcFuyDVO85Bdjz8zKCQZPF/Yr3btH
qjARDaaOu9W2ViEYxdLFXncvx9FofVutHJ8o+AOd6jFHO1CBAhBbAzqIDkb9ak37Qz3ZywH20r5R6Vc+sTn81BY+5lu
i3gSqgACvtPi3HmWr9BeRsaPpEjScGFpgyVK3zd4R5Pku0Q3iyThljLUQXpn2BWusIkOgKd7Grx6wAncWql0Lww47hV
Owc0U79RdCCcovvd9QVtEeY0uNvpWhDGmU1UPOmnqNKJlBjOoMoakHFA6w0rx8wJphYUwtDBHe6EyHOqN2GI7mxAROF
o8ucVSKJcFDSdfqIMbLdFwZe/RiaobcI86x9pWNW/syJL3WzqzFo3zzgz2vlGtalpjNWU6Xy1vo5bVvyKYPPmBP+ljH
7XMXoRpUHgcTqmUG43T5/rj4qMQiTosOjVN0hcFm2kBIh0m6RPNEAYsSpTKRQZ05GCGBle+gHw1mGAgYkKKyGSWik70
KksVhpDZ52juOFZPiXbOvnjmydcC6Pd0TL2JSYgnhbflN2Jmn2xHbKs33YndIlkyNMQ8lN1uF/5EFhtVJQpDCSaNAI1
L+GedbCuL6UmCebd3tFfLLDuCIScXf+IryluBjzH/utw4qwc5YqbTHGi0FlbmzPsosezyED76ao7V5stmswava9Bsrr
BKqRop8Ci7P+T2wnIYJw7DTHSd36suWaD9r7hnmnytOOtMHLgnKO6vzN2NOjZ5/NvLLO5s2/+CrrBD/ALehrWw/auTe
9cNFgdYMe/XOYsiKEy0In96KFRR2kHK/scYzXf6/wnJNDJqagkAAA==
END_CODEGEN_DATA
*/
