/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: 9ee79f5a-a180-4003-9eca-d95b6cf42c3c
*/

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace currencyAPI.ControllersTests
{
	[TestClass]
	public class GetCurrencyChangesTestCase
	{
#region Test methods
		[TestMethod]
		public async Task GetCurrencyChangesTest()
		{
			var tests = this.GetDataForExpectedReturnValueTests();
			foreach (var data in tests)
			{
				var parameters = data.Params;
				var actual = await data.ObjectUnderTest.GetCurrencyChanges(parameters.Currency);
				Assert.AreEqual(data.ExpectedValue, actual, data.Name);
			}
		}
#endregion

#region Test data
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public IEnumerable<ExpectedValueTestData<IEnumerable<currencyAPI.Models.GetCurrencyChanges>>> GetDataForExpectedReturnValueTests()
		{
			yield return new ExpectedValueTestData<IEnumerable<currencyAPI.Models.GetCurrencyChanges>>
			{
				Name = @"p1",
				ObjectUnderTest = new currencyAPI.Controllers.CurrencyChangesController(),
				Params = new Parameters
				{
					Currency = "USD"
				},
				ExpectedValue = null
			};
		}
#endregion

#region Types
//=========================================================================================================================
//Please modify this section only in the Modeleditor not here in the code, because otherwise it will cause merge conflicts!
//=========================================================================================================================
		public struct ExpectedValueTestData<TExpected>
		{
			public string Name;
			public currencyAPI.Controllers.CurrencyChangesController ObjectUnderTest;
			public Parameters Params;
			public TExpected ExpectedValue;
		}

		public struct Parameters
		{
			public string Currency;
		}
#endregion
	}
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAAAO1VW08aQRR+hoT/MMUXNLBo1bYUJTWALQ8IkdWkafowzB5g2mEWZ2alm8b/3nP2wk1t2qSJLyWE7Jz
Ldy7zfWz9oFQ8YJ0Buxr4rD/o9C4/M/9Tb8Tag36/e+WT9yNoMNxBwMYxC+B+js9k98E6Ng8DUO9ZA+BtY3LKa/zo3W
Ht5PDwuNYAwWtB43T8RkxOXotjgTn1UrFUjKzUUzaKrYN5c/votUOlQDgZausldaXYDbmGSRay6/FnBniABs/n9rtdu
ftSmNCGE+fdShtxNXJRIEOP+vfDUFnvRktHJwxuUoeaz8EuuAAmImNAi/hi2MPetDPUn7EUbEvFn6Vi4Qs9txW39iue
FtFYScEEnXFxrp3lt2dcTyHJa3OL6ytg7p6BKY6RLRLcLAwQtJBC9pMzYeag3MZaMBrtGeTKPkVTU4XCPTfMUZfsnLm
ZpG26Dnf8MjTdHwvcHwTX4CKjb7mKIJmnst9MUichrlHMWIUwAsxhUqdYCX5WIKmw4AZX5XAjWIZCvSFZbHMdwoXDla
ObL7l0adBg/A07uNEBGKrsPR6nskb2clfWXuHCWjDOuzDQvUPoSgKZD5WMU82qVtNyV4iUJT/QL/7sgQ7S7dN9b10Ep
ZSK9fr5S32o+FAB0oTUJSdxcoHMpqRnoVZxciMzYH1SHwTShYbp0LEZGMh9An1VNkYVRogUosksJT7hJSylUiy1z8FM
KVZPkGLOvnrhyVdk73V1hL3xsYKzrbulOyIin21GbMo02Yl9glOtVov9iQrWIoolqICZJIJpWLJ/1smmkIieqI8P5cV
RuZqadgSCXqr+zJ+Rt4O+dlX2M7xUlRnMcCWt1Jm1UchhMKx8M+qUU/NDBrE1OiFFSqWSav5eU/EC7H89vdDkKz1ZZy
LhniGwn5tba+6v8+gVShxtbtr/motsh9NbaGtKss0XSOZdtbfdfs67x1NuM/ypefI2n+IunfH7C+2ANvwbCQAA
END_CODEGEN_DATA
*/
